[project]
name = "ci-cd-connect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.6",
    "pandas>=2.3.0",
    "scikit-learn>=1.6.1",
]
